# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

include make.inc

LIB_NAME = tidl_api.lib

CRT_ROOT    ?= $(TVM_ROOT)/src/runtime/crt
CRT_CONFIG  ?= .
DLPACK_ROOT ?= $(TVM_ROOT)/3rdparty/dlpack
BUILD_DIR   ?= build

TI_MEM_MANAGER_SRC = $(USE_TIDL_RT_PATH)/../../common/ti_mem_manager.c
# new path after moving ti_dl/rt to arm-tidl/rt
ifeq ("$(wildcard $(TI_MEM_MANAGER_SRC))", "")
  TI_MEM_MANAGER_SRC = $(USE_TIDL_RT_PATH)/test/src/ti_mem_manager.c
endif

CFLAGS += -I $(TVM_ROOT)/include -I $(DLPACK_ROOT)/include
CFLAGS += -I $(CRT_ROOT)/include -I $(CRT_CONFIG) -I $(USE_TIDL_RT_PATH)/inc
CFLAGS += -I $(USE_TIDL_RT_PATH)/../inc -I $(USE_TIDL_RT_PATH)/../../common
# new path after moving ti_dl/rt to arm-tidl/rt
CFLAGS += -I $(USE_TIDL_RT_PATH)/inc -I $(USE_TIDL_RT_PATH)/test/src
CFLAGS += -I $(IVISION_PATH)
CFLAGS += -I $(PDK_PATH)/packages

SOURCES = bundle_static.c \
          tidl_api.c \
          tidl_api_mem.c \
          tvm_tidl_dmautils.c \
          tvm_tidl_sort.c

HEADERS := $(shell find . -name "*.h")
OBJS  = $(patsubst %.c,$(BUILD_DIR)/%.obj,$(SOURCES))
OBJS += $(BUILD_DIR)/ti_mem_manager.obj
OBJS += $(BUILD_DIR)/tidl_rt_ovx_debug_utils.obj

all: $(LIB_NAME)

$(LIB_NAME): $(OBJS)
	$(QUIET)$(AR) -r $@ $^

$(BUILD_DIR)/%.obj: %.c $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< -fr=$(BUILD_DIR)

$(BUILD_DIR)/%.obj: $(TI_MEM_MANAGER_SRC) $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< -fr=$(BUILD_DIR)

# tidl_rt_ovx_debug_utils.c uses "%llu" to print 32-bit integer, which does not work on C7x.
# Patch the released code in PSDK 8.4 to use "%u".
# Once the TIDL RT src code is fixed, remove this rule and use TIDL RT src directly.
$(BUILD_DIR)/tidl_rt_ovx_debug_utils.c: $(USE_TIDL_RT_PATH)/src/tidl_rt_ovx_debug_utils.c
	$(QUIET)$(MKDIR_P) $(dir $@)
	cp $< $@
	sed -i 's/llu,/u,/' $@

$(BUILD_DIR)/tidl_rt_ovx_debug_utils.obj: $(BUILD_DIR)/tidl_rt_ovx_debug_utils.c $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< -fr=$(BUILD_DIR)

clean:
	$(QUIET)$(RMDIR) $(LIB_NAME) $(OBJS)

.PHONY: all
.DEFAULT_GOAL: all
