# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

include make.inc

ifeq ($(TARGET_PLATFORM), PC)
  LIB_NAME = $(SILICON_VERSION)/libtidl_api.a
	HOSTEMU_SOURCE = tvm_tidl_hostemu.c
else
  LIB_NAME = $(SILICON_VERSION)/tidl_api.lib
	HOSTEMU_SOURCE =
endif

CRT_ROOT    ?= $(TVM_ROOT)/src/runtime/crt
CRT_CONFIG  ?= .
DLPACK_ROOT ?= $(TVM_ROOT)/3rdparty/dlpack
BUILD_DIR   ?= $(SILICON_VERSION)/$(BUILD_DIR_NAME)

TI_MEM_MANAGER_C = $(USE_TIDL_RT_PATH)/test/src/ti_mem_manager.c
TIDL_RT_OVX_DEBUG_UTILS_C = $(USE_TIDL_RT_PATH)/src/tidl_rt_ovx_debug_utils.c

# Find TIOVX path - look for it relative to IVISION_PATH or PDK_PATH
TIOVX_PATH ?= $(shell dirname $(IVISION_PATH))/tiovx

CFLAGS += -I $(TVM_ROOT)/include -I $(DLPACK_ROOT)/include
CFLAGS += -I $(CRT_ROOT)/include -I $(CRT_CONFIG)
CFLAGS += -I $(USE_TIDL_RT_PATH)/inc -I $(USE_TIDL_RT_PATH)/test/src -I $(USE_TIDL_RT_PATH)/src
CFLAGS += -I $(IVISION_PATH)
CFLAGS += -I $(PDK_PATH)
CFLAGS += -I $(DMAUTILS_PATH)
# Add TIOVX include paths for TI/tivx.h and related headers
CFLAGS += -I $(TIOVX_PATH)/include
CFLAGS += -I $(TIOVX_PATH)/kernels/include
# Add TIDL TIOVX kernels include path for TI/j7_tidl.h
CFLAGS += -I $(USE_TIDL_RT_PATH)/../tiovx_kernels/include

SOURCES = bundle_static.c \
          tidl_api.c \
          tidl_api_mem.c \
          tvm_tidl_dmautils.c \
          tvm_tidl_sort.cc $(HOSTEMU_SOURCE)

HEADERS := $(shell find . -name "*.h")
OBJS_C  = $(patsubst %.c,$(BUILD_DIR)/%.obj,$(SOURCES))
OBJS  = $(patsubst %.cc,$(BUILD_DIR)/%.obj,$(OBJS_C))

OBJS += $(BUILD_DIR)/ti_mem_manager.obj
OBJS += $(BUILD_DIR)/tidl_rt_ovx_debug_utils.obj

all: $(LIB_NAME)

$(LIB_NAME): $(OBJS)
	$(QUIET)$(AR) -r $@ $^

$(BUILD_DIR)/%.obj: %.cc $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CXX) $(CFLAGS) $(CXXFLAGS) -c $< $(OPTION_OUTFILE) $@

$(BUILD_DIR)/%.obj: %.c $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< $(OPTION_OUTFILE) $@

$(BUILD_DIR)/%.obj: $(TI_MEM_MANAGER_C) $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< $(OPTION_OUTFILE) $@

$(BUILD_DIR)/tidl_rt_ovx_debug_utils.obj: $(TIDL_RT_OVX_DEBUG_UTILS_C)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< $(OPTION_OUTFILE) $@

clean:
	$(QUIET)$(RMDIR) $(LIB_NAME) $(OBJS) $(SILICON_VERSION)

.PHONY: all
.DEFAULT_GOAL: all
