# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

EXE_NAME = dsp_syms.out

BUILD_DIR   ?= build

ifeq (, $(shell which cl7x))
    CC=$(CGT7X_ROOT)/bin/cl7x
    CXX=$(CGT7X_ROOT)/bin/cl7x
    AR=$(CGT7X_ROOT)/bin/ar7x
    STRIP=$(CGT7X_ROOT)/bin/strip7x
    export C7X_C_DIR=$(CGT7X_ROOT)/include;$(CGT7X_ROOT)/lib
else
    CC=cl7x
    CXX=cl7x
    AR=ar7x
    STRIP=strip7x
endif

MKDIR_P = mkdir -p
RMDIR = rm -fr
QUIET  ?= @

PKG_CFLAGS  = -o3 -mv7100 --abi=eabi --gcc --c11 -DSOC_J721E
CFLAGS += $(PKG_CFLAGS)


all: $(EXE_NAME) $(EXE_NAME).obj

$(BUILD_DIR)/dsp_syms.obj: dsp_syms.c
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< --output_file $@

dsp_syms.out: $(BUILD_DIR)/dsp_syms.obj
	$(QUIET)$(CC) $^ -z --dynamic=exe --no_entry_point --soname=$@ -o $@
	$(QUIET)$(STRIP) $@

$(BUILD_DIR)/dsp_syms.out.asm: dsp_syms.out
	python3 ./gen_c7x_sect.py $< $@

dsp_syms.out.obj: $(BUILD_DIR)/dsp_syms.out.asm
	$(QUIET)$(CC) $(CFLAGS) $< --output_file $@

clean:
	$(QUIET)$(RMDIR) $(EXE_NAME) $(EXE_NAME).obj $(BUILD_DIR)

