# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

cur_mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
include $(dir $(cur_mkfile_path))/make.inc

DLPACK_ROOT ?= $(TVM_ROOT)/3rdparty/dlpack


ifeq ($(TARGET_PLATFORM), PC)
### Begin host emulation setup

  EXE_NAME = libc7x_deploy_tvm_hostemu.so
	ASCXXFLAGS =

  ASM_SOURCES = $(wildcard *_embed.s)
  OBJS = $(patsubst %.s,%.obj,$(ASM_SOURCES))

  # 7120_{j721s2, _j784s4a} use the 7120 lib, remove substring after 7120
  # 7524 uses 7524-MMA2_256 for now (vs 7524-MMA_256F, floating point version)
  TMP_RTS_LIB = $(patsubst 7120%,7120,$(SILICON_VERSION))
  RTS_LIB = C$(patsubst 7524,7524-MMA2_256,$(TMP_RTS_LIB))-host-emulation

### End host emulation setup
else
### Begin c7x cross compilation setup

  EXE_NAME = c7x_deploy_tvm.out
	ASCXXFLAGS = --cpp_default

  ASM_SOURCES = $(wildcard *_embed.asm)
  OBJS = $(patsubst %.asm,%.obj,$(ASM_SOURCES))

  # 7120_{j721s2, _j784s4a} use the 7120 lib, remove substring after 7120
  RTS_LIB = rts$(patsubst 7120%,7120,$(SILICON_VERSION))_le.lib

### End c7x cross compilation setup
endif


CFLAGS += -I $(TVM_ROOT)/include -I $(DLPACK_ROOT)/include
CFLAGS += -I $(TVM_C7X_ROOT)

SOURCES  = func_registry.c tvm_main.c
SOURCES += $(wildcard model_*.c)
OBJS    +=$(patsubst %.c,%.obj,$(SOURCES))


CGT7X_EXT_LIBS ?=

all: $(EXE_NAME)

model_%.obj: model_%.c
	$(QUIET)$(CXX) $(CFLAGS) $(CXXFLAGS) $(ASCXXFLAGS) -c $(OPTION_OUTFILE) $@ $<

%.obj: %.c
	$(QUIET)$(CC) $(CFLAGS) -c $(OPTION_OUTFILE) $@ $<

%.obj: %.asm
	$(QUIET)$(CC) $(CFLAGS) -c $(OPTION_OUTFILE) $@ $<

%.obj: %.s
	$(QUIET)$(CC) $(CFLAGS) -c $(OPTION_OUTFILE) $@ $<

#### host emulation target
%.so: $(OBJS)
	$(QUIET)$(CC) -shared $(OBJS) \
            -L $(TVM_C7X_ROOT)/$(SILICON_VERSION) \
            -L $(CGT7X_ROOT)/host_emulation \
            -L $(TIDL_TOOLS_PATH) \
               -l tidl_api \
               -l tvm_crt \
               $(CGT7X_EXT_LIBS) \
            -o $@ -Wl,-soname,$@
	$(QUIET)$(STRIP) $@

# No need to include RTS_LIB, it is already linked into libvx_tidl_rt.so
#     otherwise, we run into double free problem in some cases
#               -l $(RTS_LIB) \
# By not linking in vx_tidl_rt, we reduce dependency for compilation, runtime will load vx_tidl_rt
#               -l vx_tidl_rt \


#### c7x cross compilation target
%.out: $(OBJS)
	$(QUIET)$(CC) $(CFLAGS) $(OBJS) \
                  $(TVM_C7X_ROOT)/$(SILICON_VERSION)/dsp_syms.out.obj \
            -z -i $(TVM_C7X_ROOT)/$(SILICON_VERSION) \
               -l tidl_api.lib \
               -l tvm_crt.lib \
               -l $(RTS_LIB) \
               $(CGT7X_EXT_LIBS) \
               -l $(TVM_C7X_ROOT)/c7x_tvm.cmd \
            -o $@ -m $@.map
	$(QUIET)$(STRIP) $@

clean:
	$(QUIET)$(RMDIR) $(OBJS) $(EXE_NAME)

.PHONY: all
.DEFAULT_GOAL: all
