# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

LIB_NAME = tidl_api.lib

TVM_ROOT    ?= ../../../../..
CRT_ROOT    ?= $(TVM_ROOT)/src/runtime/crt
CRT_CONFIG  ?= $(TVM_ROOT)/apps/bundle_deploy/crt_config/
DLPACK_ROOT ?= $(TVM_ROOT)/3rdparty/dlpack
BUILD_DIR   ?= build

TIDL_COMMON_PATH = $(USE_TIDL_RT_PATH)/../../common

# also requires, question
# -I $(USE_TIDL_RT_PATH)/../inc -I $(USE_TIDL_RT_PATH)/../../common
# -I $(IVISION_PATH)
# -I $(PDK_PATH)/packages
# ? consolidate with PSDKR_PATH ? then TIDL, IVISION, PDK all comes from PSDKR path

ifeq (, $(shell which cl7x))
    CC=$(CGT7X_ROOT)/bin/cl7x
    CXX=$(CGT7X_ROOT)/bin/cl7x
    AR=$(CGT7X_ROOT)/bin/ar7x
    export C7X_C_DIR=$(CGT7X_ROOT)/include;$(CGT7X_ROOT)/lib
else
    CC=cl7x
    CXX=cl7x
    AR=ar7x
endif

MKDIR_P = mkdir -p
RMDIR = rm -fr
QUIET  ?= @

PKG_CFLAGS  = -o3 -mv7100 --abi=eabi --gcc --c11 -DSOC_J721E

CFLAGS += $(PKG_CFLAGS) -I $(TVM_ROOT)/include -I $(DLPACK_ROOT)/include
CFLAGS += -I $(CRT_ROOT)/include -I $(CRT_CONFIG) -I $(USE_TIDL_RT_PATH)/inc
CFLAGS += -I $(USE_TIDL_RT_PATH)/../inc -I $(USE_TIDL_RT_PATH)/../../common
CFLAGS += -I $(IVISION_PATH)
CFLAGS += -I $(PDK_PATH)/packages

SOURCES = bundle_static.c \
          convert.c \
          tidl_api.c \
          tidl_api_mem.c \
          tvm_tidl_dmautils.c

HEADERS := $(shell find . -name "*.h")
OBJS  = $(patsubst %.c,$(BUILD_DIR)/%.obj,$(SOURCES))
OBJS += $(BUILD_DIR)/ti_mem_manager.obj

all: $(LIB_NAME)

$(LIB_NAME): $(OBJS)
	$(QUIET)$(AR) -r $@ $^

$(BUILD_DIR)/%.obj: %.c $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< -fr=$(BUILD_DIR)

$(BUILD_DIR)/%.obj: $(TIDL_COMMON_PATH)/ti_mem_manager.c $(HEADERS)
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $< -fr=$(BUILD_DIR)

clean:
	$(QUIET)$(RMDIR) $(LIB_NAME) $(OBJS)

.PHONY: all
.DEFAULT_GOAL: all
