# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

include make.inc

ifeq ($(TARGET_PLATFORM), PC)
  LIB_NAME = $(SILICON_VERSION)/libtvm_crt.a
else
  LIB_NAME = $(SILICON_VERSION)/tvm_crt.lib
endif

CRT_ROOT    ?= $(TVM_ROOT)/src/runtime/crt
CRT_CONFIG  ?= .
DLPACK_ROOT ?= $(TVM_ROOT)/3rdparty/dlpack
BUILD_DIR   ?= $(SILICON_VERSION)/$(BUILD_DIR_NAME)

CFLAGS += -I $(TVM_ROOT)/include -I $(DLPACK_ROOT)/include
CFLAGS += -I $(CRT_ROOT)/include -I $(CRT_CONFIG)

COMMON_O_FILES=$(patsubst $(CRT_ROOT)/common/%.c,$(BUILD_DIR)/common/%.o,$(wildcard $(CRT_ROOT)/common/*.c))
GRAPHRT_O_FILES=$(patsubst $(CRT_ROOT)/graph_executor/%.c,$(BUILD_DIR)/graph_executor/%.o,$(wildcard $(CRT_ROOT)/graph_executor/*.c))
MEMORY_O_FILES=$(patsubst $(CRT_ROOT)/memory/%.c,$(BUILD_DIR)/memory/%.o,$(wildcard $(CRT_ROOT)/memory/*.c))

all: $(LIB_NAME)

$(BUILD_DIR)/common/%.o: $(CRT_ROOT)/common/%.c
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $(OPTION_OUTFILE) "$@" "$<"

$(BUILD_DIR)/graph_executor/%.o: $(CRT_ROOT)/graph_executor/%.c
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $(OPTION_OUTFILE) "$@" "$<"

$(BUILD_DIR)/memory/%.o: $(CRT_ROOT)/memory/%.c
	$(QUIET)$(MKDIR_P) $(dir $@)
	$(QUIET)$(CC) $(CFLAGS) -c $(OPTION_OUTFILE) "$@" "$<"

$(LIB_NAME): $(COMMON_O_FILES) $(GRAPHRT_O_FILES) $(MEMORY_O_FILES)
	$(QUIET)$(AR) -r "$@" $^


clean:
	$(QUIET)$(RMDIR) "$(BUILD_DIR)" $(LIB_NAME) $(SILICON_VERSION)

.PHONY: all
.DEFAULT_GOAL: all
