set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_PROCESSOR aarch64)
set (MACHINE_NAME aarch64-linux-gnu)

set (TOOLS_PATH $ENV{ARM64_GCC_PATH})
set (CMAKE_C_COMPILER ${TOOLS_PATH}/bin/aarch64-none-linux-gnu-gcc)
set (CMAKE_CXX_COMPILER ${TOOLS_PATH}/bin/aarch64-none-linux-gnu-g++)
#set (CMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu)

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)