NAME ?= topk_1d
SRC_DIR ?= .
BUILD_DIR ?= artifacts_topk_ext_data

include ../../../../../src/runtime/contrib/tidl/c7x/make.inc

CFLAGS += -I../../../../../3rdparty/dlpack/include/
CFLAGS += -I../../../../../src/runtime/contrib/tidl/c7x
CFLAGS += -I$(BUILD_DIR)

$(BUILD_DIR)/$(NAME).lib: $(BUILD_DIR)/$(NAME).obj
	$(QUIET)$(MKDIR_P) $(BUILD_DIR)
	$(QUIET)$(AR) -r $@ $^

$(BUILD_DIR)/$(NAME).obj: $(SRC_DIR)/$(NAME).cpp
	$(QUIET)$(MKDIR_P) $(BUILD_DIR)
	$(QUIET)$(CXX) $(CFLAGS) -k -c $<  -fs $(BUILD_DIR) -fr $(BUILD_DIR)

clean:
	$(QUIET)$(RM) $(BUILD_DIR)/*.obj $(BUILD_DIR)/*.lib $(BUILD_DIR)/*.asm
